"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { assessIngredient, daysUntilExpiry } from "@/lib/domain/inventory";

type Product={id:string;name:string;quantity:number|null;unit:string|null;expiry_date:string|null;ingredient_id?:string|null};
type Shopping={id:string;name:string;done:boolean};
type Recipe={id:string;name:string;recipe_type:"system"|"user";is_favorite:boolean|null};
type Ingredient={id:string;recipe_id:string;name:string;quantity:number|null;unit:string|null;optional:boolean|null;ingredient_id?:string|null};
type Plan={id:string;recipe_id:string;meal_type:string};

export default function DashboardPanel({householdId,products,shopping,onNavigate}:{householdId:string;products:Product[];shopping:Shopping[];onNavigate:(tab:"products"|"shopping"|"recipes"|"plan")=>void}){
 const supabase=useMemo(()=>createClient(),[]); const [recipes,setRecipes]=useState<Recipe[]>([]); const [ingredients,setIngredients]=useState<Ingredient[]>([]); const [today,setToday]=useState<Plan[]>([]); const [loading,setLoading]=useState(true); const now=new Date(); const date=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;
 useEffect(()=>{let active=true;(async()=>{const r=await supabase.from("recipes").select("id,name,recipe_type,is_favorite").or(`recipe_type.eq.system,household_id.eq.${householdId}`).eq("is_primary_variant",true).order("name").limit(120);const ids=(r.data??[]).map(item=>item.id);const [i,p]=await Promise.all([ids.length?supabase.from("recipe_ingredients").select("id,recipe_id,name,quantity,unit,optional,ingredient_id").in("recipe_id",ids):Promise.resolve({data:[],error:null}),supabase.from("meal_plan").select("id,recipe_id,meal_type").eq("household_id",householdId).eq("planned_date",date)]);if(!active)return;setRecipes((r.data??[]) as Recipe[]);setIngredients((i.data??[]) as Ingredient[]);setToday(p.data??[]);setLoading(false)})();return()=>{active=false}},[date,householdId,supabase]);
 const suggestions=recipes.map(recipe=>{const required=ingredients.filter(i=>i.recipe_id===recipe.id&&!i.optional);const ready=required.filter(i=>assessIngredient(i,products).enough).length;return{recipe,score:required.length?Math.round(ready/required.length*100):100}}).sort((a,b)=>b.score-a.score||Number(Boolean(b.recipe.is_favorite))-Number(Boolean(a.recipe.is_favorite))).slice(0,3);
 const expiring=products.filter(p=>p.expiry_date&&daysUntilExpiry(p.expiry_date)>=0&&daysUntilExpiry(p.expiry_date)<=3).sort((a,b)=>a.expiry_date!.localeCompare(b.expiry_date!)).slice(0,4); const activeShopping=shopping.filter(i=>!i.done).slice(0,4); const mealName=(id:string)=>recipes.find(r=>r.id===id)?.name??"Рецепт";
 if(loading)return <section className="dashboard-card"><div className="empty-state">Собираем обзор кухни...</div></section>;
 return <section className="home-dashboard"><div className="dashboard-welcome"><span className="card-label">СЕГОДНЯ НА КУХНЕ</span><h2>Что происходит сегодня?</h2><div className="quick-actions"><button onClick={()=>onNavigate("products")}>+ Продукт</button><button onClick={()=>onNavigate("shopping")}>+ Покупка</button><button onClick={()=>onNavigate("recipes")}>+ Рецепт</button><button onClick={()=>onNavigate("plan")}>Запланировать</button></div></div><div className="home-grid"><article className="dashboard-card"><h3>Сегодня</h3>{today.length?today.map(item=><button className="dashboard-line" key={item.id} onClick={()=>onNavigate("plan")}><span>{item.meal_type==="breakfast"?"☀️":item.meal_type==="lunch"?"🍲":"🌙"}</span><strong>{mealName(item.recipe_id)}</strong></button>):<p className="muted">Блюда пока не запланированы.</p>}</article><article className="dashboard-card"><h3>Что приготовить</h3>{suggestions.length?suggestions.map(item=><button className="dashboard-line" key={item.recipe.id} onClick={()=>onNavigate("recipes")}><strong>{item.recipe.name}</strong><span>{item.score}%</span></button>):<p className="muted">Добавьте продукты или рецепты.</p>}</article><article className="dashboard-card"><h3>Скоро испортится</h3>{expiring.length?expiring.map(item=><div className="dashboard-line" key={item.id}><strong>{item.name}</strong><span>{item.expiry_date}</span></div>):<p className="muted">Срочных продуктов нет.</p>}</article><article className="dashboard-card"><h3>Покупки · {shopping.filter(i=>!i.done).length}</h3>{activeShopping.length?activeShopping.map(item=><button className="dashboard-line" key={item.id} onClick={()=>onNavigate("shopping")}><strong>{item.name}</strong></button>):<p className="muted">Список пуст.</p>}</article></div></section>
}
