"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { assessIngredient, formatQuantity, namesMatch, normalizeName, normalizeUnit, toCanonical } from "@/lib/domain/inventory";

type Product = { id: string; name: string; quantity: number | null; unit: string | null; expiry_date?: string | null };
type Recipe = { id: string; name: string; description: string | null; instructions: string | null; servings: number | null };
type Ingredient = { id: string; recipe_id: string; name: string; quantity: number | null; unit: string | null; optional: boolean | null };
type PlanItem = { id: string; recipe_id: string; planned_date: string; meal_type: string; servings: number | null; notes: string | null; cooked_at: string | null };
type Props = { householdId: string; userId: string; products: Product[] };
type PreviewItem = { ingredient: Ingredient; needed: number | null; canonicalUnit: string | null; available: number; enough: boolean; deductions: { ingredient_id: string; product_id: string; quantity: number }[] };

const MEALS = [{ key: "breakfast", label: "Завтрак", icon: "☀️" }, { key: "lunch", label: "Обед", icon: "🍲" }, { key: "dinner", label: "Ужин", icon: "🌙" }];
function isoDate(date: Date) { const year=date.getFullYear(); const month=String(date.getMonth()+1).padStart(2,"0"); const day=String(date.getDate()).padStart(2,"0"); return `${year}-${month}-${day}`; }
function formatDay(date: Date) { return new Intl.DateTimeFormat("ru-RU", { weekday: "short", day: "numeric", month: "short" }).format(date); }

export default function MealPlanPanel({ householdId, userId, products }: Props) {
  const supabase = useMemo(() => createClient(), []);
  const [recipes, setRecipes] = useState<Recipe[]>([]); const [ingredients, setIngredients] = useState<Ingredient[]>([]); const [items, setItems] = useState<PlanItem[]>([]);
  const [weekStart, setWeekStart] = useState(() => { const date = new Date(); const day = date.getDay(); date.setDate(date.getDate() + (day === 0 ? -6 : 1 - day)); return isoDate(date); });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [error, setError] = useState(""); const [selected, setSelected] = useState<PlanItem | null>(null); const [cookOpen, setCookOpen] = useState(false); const [weekShoppingOpen, setWeekShoppingOpen] = useState(false);
  const days = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(`${weekStart}T12:00:00`); date.setDate(date.getDate() + index); return { date: isoDate(date), label: formatDay(date), isToday: isoDate(date) === isoDate(new Date()) }; }), [weekStart]);

  const load = useCallback(async (showLoading = true) => {
    if (showLoading) setLoading(true); setError(""); const end = days[6].date;
    const [recipeResult, ingredientResult, planResult] = await Promise.all([
      supabase.from("recipes").select("id,name,description,instructions,servings").or(`recipe_type.eq.system,household_id.eq.${householdId}`).eq("is_primary_variant",true).order("name").limit(200),
      supabase.from("recipe_ingredients").select("id,recipe_id,name,quantity,unit,optional").order("created_at"),
      supabase.from("meal_plan").select("id,recipe_id,planned_date,meal_type,servings,notes,cooked_at").eq("household_id", householdId).gte("planned_date", weekStart).lte("planned_date", end).order("planned_date"),
    ]);
    if (recipeResult.error) setError(recipeResult.error.message); else setRecipes(recipeResult.data ?? []);
    if (ingredientResult.error) setError(ingredientResult.error.message); else setIngredients(ingredientResult.data ?? []);
    if (planResult.error) setError(planResult.error.message); else setItems(planResult.data ?? []);
    if (showLoading) setLoading(false);
  }, [days, householdId, supabase, weekStart]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const channel = supabase.channel(`meal-plan-${householdId}`).on("postgres_changes", { event: "*", schema: "public", table: "meal_plan", filter: `household_id=eq.${householdId}` }, () => void load(false)).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [householdId, load, supabase]);

  const selectedRecipe = selected ? recipes.find((recipe) => recipe.id === selected.recipe_id) ?? null : null;
  const selectedIngredients = selected ? ingredients.filter((ingredient) => ingredient.recipe_id === selected.recipe_id) : [];
  const preview = useMemo<PreviewItem[]>(() => {
    if (!selected || !selectedRecipe) return [];
    const factor = (selected.servings ?? selectedRecipe.servings ?? 1) / (selectedRecipe.servings || 1);
    return selectedIngredients.map((ingredient) => {
      const assessment = assessIngredient(ingredient, products, factor);
      return { ingredient, needed: assessment.needed, canonicalUnit: assessment.unit, available: assessment.available ?? 0, enough: assessment.enough, deductions: assessment.deductions };
    });
  }, [products, selected, selectedIngredients, selectedRecipe]);
  const missing = preview.filter((entry) => !entry.ingredient.optional && !entry.enough);
  const weekShortages = useMemo(() => {
    const totals = new Map<string, { name: string; quantity: number | null; unit: string | null }>();
    for (const planItem of items) {
      if (planItem.cooked_at) continue;
      const recipe = recipes.find((entry) => entry.id === planItem.recipe_id); const factor = (planItem.servings ?? recipe?.servings ?? 1) / (recipe?.servings || 1);
      for (const ingredient of ingredients.filter((entry) => entry.recipe_id === planItem.recipe_id && !entry.optional)) {
        const unit = normalizeUnit(ingredient.unit); const key = `${normalizeName(ingredient.name)}:${unit ?? ""}`; const current = totals.get(key);
        const quantity = ingredient.quantity === null ? null : toCanonical(ingredient.quantity * factor, ingredient.unit).quantity;
        totals.set(key, { name: current?.name ?? ingredient.name, unit, quantity: current?.quantity === null || quantity === null ? null : (current?.quantity ?? 0) + quantity });
      }
    }
    return [...totals.values()].map((need) => {
      const available = products.filter((product) => namesMatch(product.name, need.name) && normalizeUnit(product.unit) === need.unit && product.quantity !== null).reduce((sum, product) => sum + toCanonical(product.quantity!, product.unit).quantity, 0);
      return { ...need, available, deficit: need.quantity === null ? null : Math.max(0, need.quantity - available) };
    }).filter((entry) => entry.quantity === null || (entry.deficit ?? 0) > 0);
  }, [ingredients, items, products, recipes]);

  function getItem(date: string, mealType: string) { return items.find((item) => item.planned_date === date && item.meal_type === mealType); }
  async function setMeal(date: string, mealType: string, recipeId: string) { const key = `${date}:${mealType}`; setSaving(key); setError(""); try { const existing = getItem(date, mealType); if (!recipeId) { if (existing) { const { error: deleteError } = await supabase.from("meal_plan").delete().eq("id", existing.id); if (deleteError) throw deleteError; setItems((current) => current.filter((item) => item.id !== existing.id)); } return; } if (existing) { const { data, error: updateError } = await supabase.from("meal_plan").update({ recipe_id: recipeId, cooked_at: null, cooked_by: null }).eq("id", existing.id).select("id,recipe_id,planned_date,meal_type,servings,notes,cooked_at").single(); if (updateError) throw updateError; setItems((current) => current.map((item) => item.id === existing.id ? data : item)); } else { const recipe = recipes.find((entry) => entry.id === recipeId); const { data, error: insertError } = await supabase.from("meal_plan").upsert({ household_id: householdId, recipe_id: recipeId, planned_date: date, meal_type: mealType, servings: recipe?.servings ?? 2, created_by: userId }, { onConflict: "household_id,planned_date,meal_type" }).select("id,recipe_id,planned_date,meal_type,servings,notes,cooked_at").single(); if (insertError) throw insertError; setItems((current) => [...current, data]); } } catch (err) { setError(err instanceof Error ? err.message : "Не удалось изменить план."); } finally { setSaving(null); } }
  async function addMissing() { if (!selected || !missing.length) return; setSaving("shopping"); const rows = missing.map(({ ingredient, needed, available, canonicalUnit }) => ({ household_id: householdId, name: ingredient.name, quantity: needed === null ? null : Math.max(0, needed - available), unit: canonicalUnit, done: false, added_from_recipe: selected.recipe_id, created_by: userId })); const { error: insertError } = await supabase.rpc("add_or_merge_shopping_items", { p_household_id: householdId, p_items: rows.map((row) => ({ name: row.name, quantity: row.quantity, unit: row.unit, recipe_id: row.added_from_recipe })) }); if (insertError) setError(insertError.message); setSaving(null); }
  async function addWeekShopping() { if (!weekShortages.length) return; setSaving("week-shopping"); setError(""); const { error: mergeError } = await supabase.rpc("add_or_merge_shopping_items", { p_household_id: householdId, p_items: weekShortages.map((item) => ({ name: item.name, quantity: item.deficit, unit: item.unit })) }); if (mergeError) setError(mergeError.message); else setWeekShoppingOpen(false); setSaving(null); }
  async function cook() { if (!selected || missing.length) return; setSaving("cook"); setError(""); const deductions = preview.filter((entry) => entry.enough).flatMap((entry) => entry.deductions); const { data, error: cookError } = await supabase.rpc("cook_meal_plan", { p_meal_plan_id: selected.id, p_deductions: deductions }); if (cookError) setError(cookError.message); else { setItems((current) => current.map((item) => item.id === selected.id ? { ...item, cooked_at: data.cooked_at } : item)); setSelected((current) => current ? { ...current, cooked_at: data.cooked_at } : null); setCookOpen(false); } setSaving(null); }
  function shiftWeek(offset: number) { const date = new Date(`${weekStart}T12:00:00`); date.setDate(date.getDate() + offset * 7); setWeekStart(isoDate(date)); }

  if (loading) return <section className="dashboard-card"><div className="empty-state">Загружаем план питания...</div></section>;
  return <section className="dashboard-card meal-plan-card"><div className="card-heading"><div><span className="card-label">ОРГАНИЗАЦИЯ ПИТАНИЯ</span><h2>План на неделю</h2></div><div className="plan-week-actions"><button className="secondary-button compact-button" onClick={() => setWeekShoppingOpen(true)}>Покупки на неделю</button><button className="secondary-button compact-button" onClick={() => shiftWeek(-1)}>←</button><button className="secondary-button compact-button" onClick={() => { const now = new Date(); const day = now.getDay(); now.setDate(now.getDate() + (day === 0 ? -6 : 1 - day)); setWeekStart(isoDate(now)); }}>Сегодня</button><button className="secondary-button compact-button" onClick={() => shiftWeek(1)}>→</button></div></div>{error && <div className="form-error">{error}</div>}{!recipes.length ? <div className="empty-state">Сначала создайте хотя бы один рецепт.</div> : <div className="meal-plan-grid">{days.map((day) => <div className={`meal-plan-day ${day.isToday ? "meal-plan-today" : ""}`} key={day.date}><div className="meal-plan-date">{day.label}{day.isToday && <span>Сегодня</span>}</div>{MEALS.map((meal) => { const item = getItem(day.date, meal.key); const recipe = item ? recipes.find((entry) => entry.id === item.recipe_id) : null; const key = `${day.date}:${meal.key}`; return <div className={`meal-slot ${item?.cooked_at ? "meal-slot-cooked" : ""}`} key={meal.key}><div className="meal-slot-label"><span>{meal.icon}</span>{meal.label}{item?.cooked_at && <b>✓</b>}</div><select value={item?.recipe_id ?? ""} onChange={(event) => setMeal(day.date, meal.key, event.target.value)} disabled={saving === key}><option value="">— Не запланировано —</option>{recipes.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select>{item && <button className="meal-open-button" onClick={() => { setSelected(item); setCookOpen(false); }}>Открыть · {recipe?.name}</button>}</div>; })}</div>)}</div>}
    {weekShoppingOpen && <div className="modal-backdrop" onMouseDown={() => setWeekShoppingOpen(false)}><div className="edit-modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><span className="card-label">ПЛАН НА НЕДЕЛЮ</span><h2>Недостающие продукты</h2></div><button className="modal-close" onClick={() => setWeekShoppingOpen(false)}>×</button></div>{weekShortages.length === 0 ? <div className="empty-state">Для запланированных блюд всего достаточно.</div> : <div className="plan-availability">{weekShortages.map((item) => <div className="availability-row shortage" key={`${normalizeName(item.name)}:${item.unit}`}><span>{item.name}</span><small>{item.deficit === null ? "укажите количество вручную" : `докупить ${formatQuantity(item.deficit, item.unit)}`}</small></div>)}</div>}<div className="modal-actions"><button className="secondary-button" onClick={() => setWeekShoppingOpen(false)}>Закрыть</button><button className="primary-button" onClick={addWeekShopping} disabled={!weekShortages.length || saving === "week-shopping"}>{saving === "week-shopping" ? "Добавляем..." : "Добавить в покупки"}</button></div></div></div>}
    {selected && selectedRecipe && <div className="modal-backdrop" onMouseDown={() => setSelected(null)}><div className="edit-modal plan-recipe-modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><span className="card-label">{selected.planned_date} · {MEALS.find((meal) => meal.key === selected.meal_type)?.label}</span><h2>{selectedRecipe.name}</h2></div><button className="modal-close" onClick={() => setSelected(null)}>×</button></div>{selectedRecipe.description && <p>{selectedRecipe.description}</p>}<div className="plan-availability"><h3>Продукты на {selected.servings ?? selectedRecipe.servings ?? 1} порц.</h3>{preview.map((entry) => <div className={`availability-row ${entry.enough ? "enough" : "shortage"}`} key={entry.ingredient.id}><span>{entry.enough ? "✓" : entry.ingredient.optional ? "○" : "!"} {entry.ingredient.name}</span><small>нужно {formatQuantity(entry.needed, entry.canonicalUnit)}{entry.needed !== null && ` · есть ${formatQuantity(entry.available, entry.canonicalUnit)}`}</small></div>)}</div>{missing.length > 0 && <div className="cook-warning">Не хватает: {missing.map((entry) => entry.ingredient.name).join(", ")}. Списание недоступно, пока продуктов недостаточно.</div>}<details className="plan-instructions"><summary>Инструкция приготовления</summary><p className="recipe-instructions">{selectedRecipe.instructions || "Инструкция пока не добавлена."}</p></details><div className="plan-modal-actions">{missing.length > 0 && <button className="secondary-button" onClick={addMissing} disabled={saving === "shopping"}>{saving === "shopping" ? "Добавляем..." : "Добавить недостающее в покупки"}</button>}<button className="primary-button" onClick={() => setCookOpen(true)} disabled={Boolean(missing.length) || Boolean(selected.cooked_at)}>{selected.cooked_at ? "Уже приготовлено" : "Приготовить"}</button></div>{cookOpen && <div className="cook-confirm"><strong>Подтвердите списание</strong><p>Остатки будут уменьшены только после подтверждения и никогда не уйдут в минус.</p>{preview.filter((entry) => entry.enough && entry.deductions.length).map((entry) => <div key={entry.ingredient.id}>{entry.ingredient.name}: −{formatQuantity(entry.needed, entry.canonicalUnit)}</div>)}<div className="modal-actions"><button className="secondary-button" onClick={() => setCookOpen(false)}>Отмена</button><button className="primary-button" onClick={cook} disabled={saving === "cook"}>{saving === "cook" ? "Списываем..." : "Подтвердить"}</button></div></div>}</div></div>}
  </section>;
}
