"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Product = { name: string; expiry_date: string | null };
type Recipe = { id: string; name: string; description: string | null; prep_time_minutes: number | null; servings: number | null; difficulty: string | null; is_favorite: boolean | null };
type Ingredient = { id: string; recipe_id: string; name: string; quantity: number | null; unit: string | null; optional: boolean | null };
type Props = { householdId: string; userId: string; products: Product[] };

function normalize(value: string) { return value.toLowerCase().replaceAll("ё", "е").trim(); }
function matches(productName: string, ingredientName: string) { const p=normalize(productName),i=normalize(ingredientName); if(p.includes(i)||i.includes(p))return true; const aliases:Record<string,string[]>={яйца:["яйцо"],макароны:["паста","спагетти","лапша"],курица:["куриное филе","куриная грудка"],помидоры:["помидор","томаты","томат"],сыр:["моцарелла","чеддер","пармезан"],лук:["репчатый лук"]}; return (aliases[i]??[]).some(a=>p.includes(a)||a.includes(p)); }

export default function RecipesPanel({ householdId, userId, products }: Props) {
  const supabase=createClient(); const [recipes,setRecipes]=useState<Recipe[]>([]); const [ingredients,setIngredients]=useState<Ingredient[]>([]); const [search,setSearch]=useState(""); const [onlyAvailable,setOnlyAvailable]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [adding,setAdding]=useState<string|null>(null);
  async function load(){setLoading(true);setError("");const [r,i]=await Promise.all([supabase.from("recipes").select("id,name,description,prep_time_minutes,servings,difficulty,is_favorite").eq("household_id",householdId).order("is_favorite",{ascending:false}).order("name"),supabase.from("recipe_ingredients").select("id,recipe_id,name,quantity,unit,optional").order("created_at")]);if(r.error)setError(r.error.message);else setRecipes(r.data??[]);if(i.error)setError(i.error.message);else setIngredients(i.data??[]);setLoading(false);}
  useEffect(()=>{load()},[householdId]);
  const scored=useMemo(()=>recipes.map(recipe=>{const ri=ingredients.filter(x=>x.recipe_id===recipe.id),required=ri.filter(x=>!x.optional),missing=required.filter(x=>!products.some(p=>matches(p.name,x.name)));return {recipe,ingredients:ri,missing,score:required.length?Math.round(((required.length-missing.length)/required.length)*100):100};}),[recipes,ingredients,products]);
  const visible=scored.filter(x=>(!search||normalize(x.recipe.name).includes(normalize(search)))&&(!onlyAvailable||x.score===100)).sort((a,b)=>b.score-a.score||Number(Boolean(b.recipe.is_favorite))-Number(Boolean(a.recipe.is_favorite)));
  async function addMissingToShopping(recipeId:string){const item=scored.find(x=>x.recipe.id===recipeId);if(!item?.missing.length)return;setAdding(recipeId);setError("");const {error:e}=await supabase.from("shopping_items").insert(item.missing.map(i=>({household_id:householdId,name:i.name,quantity:i.quantity,unit:i.unit,done:false,added_from_recipe:recipeId,created_by:userId})));if(e)setError(e.message);setAdding(null);}
  if(loading)return <section className="dashboard-card"><div className="empty-state">Загружаем рецепты...</div></section>;
  return <section className="dashboard-card recipes-card"><div className="card-heading"><div><span className="card-label">УМНЫЙ ПОДБОР</span><h2>Что приготовить?</h2></div><span className="count-badge">{recipes.length}</span></div><div className="recipe-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Найти рецепт..."/><label className="recipe-filter"><input type="checkbox" checked={onlyAvailable} onChange={e=>setOnlyAvailable(e.target.checked)}/> Только из того, что есть</label></div>{error&&<div className="form-error">{error}</div>}{!recipes.length?<div className="empty-state">Рецептов пока нет.</div>:<div className="recipe-grid">{visible.map(({recipe,ingredients:ri,missing,score})=><article className="recipe-card" key={recipe.id}><div className={`recipe-score ${score===100?"perfect":""}`}>{score}%</div><div className="recipe-title-row"><h3>{recipe.name}</h3>{recipe.is_favorite&&<span>★</span>}</div>{recipe.description&&<p className="recipe-description">{recipe.description}</p>}<div className="recipe-meta">{recipe.prep_time_minutes?`⏱ ${recipe.prep_time_minutes} мин`:"⏱ Время не указано"}{recipe.servings?` · 👥 ${recipe.servings}`:""}{recipe.difficulty?` · ${recipe.difficulty}`:""}</div><div className="recipe-ingredients">{ri.map(i=>{const available=products.some(p=>matches(p.name,i.name));return <span className={`ingredient ${available?"available":i.optional?"optional":"missing"}`} key={i.id}>{available?"✓":i.optional?"○":"+"} {i.name}</span>})}</div>{score===100?<p className="recipe-perfect">🎉 Всё необходимое уже есть дома</p>:missing.length&&<><p className="recipe-missing">Не хватает: {missing.map(i=>i.name).join(", ")}</p><button className="secondary-button recipe-shopping-button" disabled={adding===recipe.id} onClick={()=>addMissingToShopping(recipe.id)}>{adding===recipe.id?"Добавляем...":"Добавить недостающее в покупки"}</button></>}</article>)}</div>}</section>;
}
