"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export type ShoppingItem = { id: string; name: string; quantity: number | null; unit: string | null; category: string | null; done: boolean; transferred_at: string | null };
type Props = { householdId: string; userId: string; items: ShoppingItem[]; onRefresh: () => Promise<void>; onError: (message: string) => void };
const UNITS = ["шт", "г", "кг", "мл", "л", "уп.", "пач."];
const CATEGORIES = ["Овощи", "Фрукты", "Мясо", "Молочные", "Бакалея", "Напитки", "Другое"];

export default function ShoppingPanel({ householdId, userId, items, onRefresh, onError }: Props) {
  const supabase = createClient(); const [name, setName] = useState(""); const [quantity, setQuantity] = useState(""); const [unit, setUnit] = useState("шт"); const [category, setCategory] = useState("Другое"); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState<ShoppingItem | null>(null); const [transfer, setTransfer] = useState<ShoppingItem | null>(null); const [expiry, setExpiry] = useState("");
  async function add() { if (!name.trim()) return; setBusy(true); const { error } = await supabase.from("shopping_items").insert({ household_id: householdId, name: name.trim(), quantity: quantity ? Number(quantity) : null, unit, category, done: false, created_by: userId }); if (error) onError(error.message); else { setName(""); setQuantity(""); await onRefresh(); } setBusy(false); }
  async function toggle(item: ShoppingItem) { const { error } = await supabase.from("shopping_items").update({ done: !item.done }).eq("id", item.id); if (error) onError(error.message); else await onRefresh(); }
  async function remove(id: string) { const { error } = await supabase.from("shopping_items").delete().eq("id", id); if (error) onError(error.message); else await onRefresh(); }
  async function saveEdit() { if (!editing?.name.trim()) return; setBusy(true); const { error } = await supabase.from("shopping_items").update({ name: editing.name.trim(), quantity: editing.quantity, unit: editing.unit, category: editing.category }).eq("id", editing.id); if (error) onError(error.message); else { setEditing(null); await onRefresh(); } setBusy(false); }
  async function addHome() { if (!transfer) return; setBusy(true); const { error } = await supabase.rpc("transfer_shopping_item_to_products", { p_shopping_item_id: transfer.id, p_quantity: transfer.quantity, p_unit: transfer.unit, p_category: transfer.category, p_expiry_date: expiry || null }); if (error) onError(error.message); else { setTransfer(null); setExpiry(""); await onRefresh(); } setBusy(false); }
  const active = items.filter((item) => !item.done); const completed = items.filter((item) => item.done);
  return <section className="dashboard-card shopping-card"><div className="card-heading"><div><span className="card-label">ОБЩИЙ СПИСОК</span><h2>Покупки</h2></div><span className="count-badge">{active.length}</span></div><div className="shopping-form"><input value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => event.key === "Enter" && add()} placeholder="Что нужно купить?"/><input type="number" min="0" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} placeholder="Кол."/><select value={unit} onChange={(event) => setUnit(event.target.value)}>{UNITS.map((value) => <option key={value}>{value}</option>)}</select><select value={category} onChange={(event) => setCategory(event.target.value)}>{CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select><button className="primary-button" onClick={add} disabled={busy}>+ Добавить</button></div><div className="shopping-list">{!items.length && <div className="empty-state">Список покупок пуст.</div>}{active.map((item) => <Row key={item.id} item={item} onToggle={toggle} onEdit={setEditing} onDelete={remove} onHome={setTransfer}/>)}{completed.length > 0 && <><div className="completed-label">Куплено</div>{completed.map((item) => <Row key={item.id} item={item} onToggle={toggle} onEdit={setEditing} onDelete={remove} onHome={setTransfer}/>)}</>}</div>
  {editing && <div className="modal-backdrop"><div className="edit-modal"><div className="modal-header"><h2>Изменить покупку</h2><button className="modal-close" onClick={() => setEditing(null)}>×</button></div><input value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })}/><div className="product-form-row"><input type="number" min="0" step="any" value={editing.quantity ?? ""} onChange={(event) => setEditing({ ...editing, quantity: event.target.value ? Number(event.target.value) : null })}/><select value={editing.unit ?? "шт"} onChange={(event) => setEditing({ ...editing, unit: event.target.value })}>{UNITS.map((value) => <option key={value}>{value}</option>)}</select></div><select value={editing.category ?? "Другое"} onChange={(event) => setEditing({ ...editing, category: event.target.value })}>{CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select><div className="modal-actions"><button className="secondary-button" onClick={() => setEditing(null)}>Отмена</button><button className="primary-button" onClick={saveEdit} disabled={busy}>Сохранить</button></div></div></div>}
  {transfer && <div className="modal-backdrop"><div className="edit-modal"><div className="modal-header"><div><span className="card-label">КУПЛЕНО</span><h2>Добавить «{transfer.name}» домой</h2></div><button className="modal-close" onClick={() => setTransfer(null)}>×</button></div><div className="product-form-row"><input type="number" min="0" step="any" value={transfer.quantity ?? ""} onChange={(event) => setTransfer({ ...transfer, quantity: event.target.value ? Number(event.target.value) : null })}/><select value={transfer.unit ?? "шт"} onChange={(event) => setTransfer({ ...transfer, unit: event.target.value })}>{UNITS.map((value) => <option key={value}>{value}</option>)}</select></div><select value={transfer.category ?? "Другое"} onChange={(event) => setTransfer({ ...transfer, category: event.target.value })}>{CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select><label className="field-label">Срок годности<input type="date" value={expiry} onChange={(event) => setExpiry(event.target.value)}/></label><div className="modal-actions"><button className="secondary-button" onClick={() => setTransfer(null)}>Отмена</button><button className="primary-button" onClick={addHome} disabled={busy}>Добавить домой</button></div></div></div>}</section>;
}
function Row({ item, onToggle, onEdit, onDelete, onHome }: { item: ShoppingItem; onToggle: (item: ShoppingItem) => void; onEdit: (item: ShoppingItem) => void; onDelete: (id: string) => void; onHome: (item: ShoppingItem) => void }) { return <div className={`shopping-item ${item.done ? "shopping-done" : ""}`}><button className="check-button" onClick={() => onToggle(item)} aria-label={item.done ? "Вернуть в покупки" : "Отметить купленным"}>{item.done ? "✓" : ""}</button><div className="shopping-name"><strong>{item.name}</strong><span className="muted">{item.quantity !== null ? `${item.quantity} ${item.unit ?? ""}` : "Без количества"}{item.category ? ` · ${item.category}` : ""}</span></div><div className="shopping-actions">{item.done && !item.transferred_at && <button className="home-button" onClick={() => onHome(item)}>Домой</button>}{item.transferred_at && <span className="home-done">Дома ✓</span>}<button className="icon-button" onClick={() => onEdit(item)} aria-label={`Изменить ${item.name}`}>✎</button><button className="delete-button" onClick={() => onDelete(item.id)} aria-label={`Удалить ${item.name}`}>×</button></div></div>; }
